aurora.controller.test:
    controller: 'aurora.controller.test'
    path:
        - '/aurora/test'
        - '/aurora/test/service'

aurora.controller.blackhole:
    controller: 'aurora.controller.blackhole:blackHole'
    path:
        - '/js/cms/panel/panel.js'
        - '/(wp|wordpress)/wp-login.php'
        - '/wp-content/plugins/mm-plugin/inc/vendors/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php'
        - '/wp-login.php'
        - '/fckeditor/editor/filemanager/connectors/php/upload.php'
        - '/xmlrpc.php'
        - '/vendor/phpunit/phpunit/phpunit.xsd'
        - '/wp-includes/wlwmanifest.xml'
        - '/admin|administrator|root)/index.php'
        - '/administrator/'
        - '/.env'
        - '/components/'

aurora.controller.pwa.progressiveWebApplication:
    controller: 'aurora.controller.pwa:favicon'
    path:
        - '/favicon.ico'
        - '/favicon-{width<\d+>}x{height<\d+>}.png'
        - '/android-icon-{width<\d+>}x{height<\d+>}.png'
        - '/apple-icon.png'
        - '/apple-icon-precomposed.png'
        - '/apple-icon-{width<\d+>}x{height<\d+>}.png'
        - '/apple-touch-icon-{width<\d+>}x{height<\d+>}.png'
        - '/apple-touch-icon-{width<\d+>}x{height<\d+>}-precomposed.png'
        - '/ms-icon-{width<\d+>}x{height<\d+>}.png'
        - '/manifest.webmanifest'
        - '/manifest.json'
        - '/pwa-main.js'
        - '/pwa-sw.js'

aurora.controller.pwa.offline:
    controller: 'aurora.controller.pwa:offline'
    path:
        - '/pwa-offline'