aurora.controller.test:
    controller: 'aurora.controller.test'
    path:
        - '/aurora/test'
        - '/aurora/test/service'

aurora.controller.blackhole:
    controller: 'aurora.controller.blackhole::blackHole'
    requirements:
        anything: '.+'
    path:
        # Wordpress
        - '/wordpress/'
        - '/wordpress/{anything}'
        - '{anything}/wordpress/'
        - '/wp/'
        - '/wp/{anything}'
        - '{anything}/wp/'
        - '/wp-admin/'
        - '/wp-admin/{anything}'
        - '/{anything}/wp-admin/'
        - '/wp-content/{anything}'
        - '/wp-includes/{anything}'
        - '/wp-login.php'
        - '/{anything}/wp-login.php'
        - '/wp-register.php'
        - '/{anything}/wp-register.php'
        - '/wp-info.php'
        - '/{anything}/wp-info.php'
        - '/{anything}/wp-includes/wlwmanifest.xml'
        - '{anything}/taf.php'
        - '/taf.php'
        - '/wp-admin/admin.php'
        - '{anything}/chosen.php'
        - 'chosen.php'
        # Joomla
        - '/nf_tracking.php'
        # eval-stdin.php
        - '/eval-stdin.php'
        - '/{anything}/eval-stdin.php'
        # upload.php & uploadify.php
        - '/upload.php'
        - '/{anything}/upload.php'
        - '/uploadify.php'
        - '/{anything}/uploadify.php'
        # xmlrpc.php & xmlrp.php
        - '/xmlrpc.php'
        - '/{anything}/xmlrpc.php'
        - '/xmlrp.php'
        - '/{anything}/xmlrp.php'
        # PHPUnit
        - '/phpunit/{anything}'
        - '/{anything}/phpunit/'
        # Others
        - '/inputs.php'
        - '/.info.php'
        - '/js/cms/panel/panel.js'
        - '/(admin|administrator|root)/index.php'
        - '/admin/ckfinder/'
        - '/FCKeditor/fckconfig.js'
        - '/data/admin/'
        - '/administrator/(help|language)/'
        - '/js/kcfinder/browse.php'
        - '/new_license.php'
        - '/license.txt'
        - '/administrator/'
        - '/.env'
        - '/.bitcoin'
        - '/wallet.dat'
        - '/backup/wallet.dat'
        - '/components/'
        - '/tmp/'
        - '/plugin/system/debug/'
        - '/router.php'
        - '/ueditor/net/controller.ashx'
        - '/mysql/'
        - '/(phpMyAdmin|myadmin|pma)/'
        - '/(data/admin|data|admin)/allowurl.txt'
        - '/config/database.yml'
        - '/rss'
        - '/feed'
        - '/feeds'

aurora.controller.pwa.favicon:
    controller: 'aurora.controller.pwa::progressiveWebApplication'
    path:
        - '/favicon.ico'
        - '/favicon-{width<\d+>}x{height<\d+>}.png'
        - '/android-icon-{width<\d+>}x{height<\d+>}.png'
        - '/android-icon-maskable.png'
        - '/apple-icon.png'
        - '/apple-icon-precomposed.png'
        - '/apple-icon-precomposed-{width<\d+>}x{height<\d+>}.png'
        - '/apple-icon-{width<\d+>}x{height<\d+>}.png'
        - '/apple-icon-{width<\d+>}x{height<\d+>}-precomposed.png'
        - '/apple-touch-icon-{width<\d+>}x{height<\d+>}.png'
        - '/apple-touch-icon-{width<\d+>}x{height<\d+>}-precomposed.png'
        - '/ms-icon-{width<\d+>}x{height<\d+>}.png'
        - '/manifest.webmanifest'
        - '/manifest.json'
        - '/browserconfig.xml'
        - '/IEconfig.xml'
        - '/pwa-main.js'
        - '/pwa-sw.js'
        - '/sw.js'

aurora.controller.pwa.offline:
    controller: 'aurora.controller.pwa::offline'
    path:
        - '/aurora/pwa-offline'
        - '/pwa-offline'

aurora.controller.compiled:
    controller: 'aurora.controller.compiled:cssJsFiles'
    path:
        - '/aurora/compiled/{fileName}'
        #- '/aurora/compiled/{fileName}.(css|js)'

# Extra routes, see `src/Resources/config/services.yaml` & `Sindla\Bundle\AuroraBundle\DependencyInjection\ExtraLoader`
aurora_extra:
    resource: .
    type: extra
