aurora.controller.test:
    controller: 'aurora.controller.test'
    path:
        - '/aurora/test'
        - '/aurora/test/service'

aurora.controller.blackhole:
    controller: 'aurora.controller.blackhole:blackHole'
    path:
        - '/.info.php'
        - '/js/cms/panel/panel.js'
        - '/wordpress/'
        - '/(wp|wordpress|blog)/wp-login.php'
        - '/(test|wordpress|blog)/wp-admin/'
        - '/wp-content/plugins/mm-plugin/inc/vendors/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php'
        - '/wp-content/plugins/jekyll-exporter/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php'
        - '/wp-content/plugins/theme-configurator/mini.php'
        - '/sites/all/libraries/mailchimp/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php'
        - '/laravel/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php'
        - '/modules/ps_facetedsearch/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php'
        - '/api/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php'
        - '/modules/autoupgrade/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php'
        - '/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php'
        - '/wp-login.php'
        - '/wp-admin/admin-ajax.php'
        - '/wp-register.php'
        - '/wp-info.php'
        - '/wp-content/themes/404.php'
        - '/wp-content/plugins/estatik/readme.txt'
        - '/fckeditor/editor/filemanager/connectors/php/upload.php'
        - '/(js/kcfinder|admin/js/kcfinder|assets/plugin/kcfinder|vendor/kcfinder|ckeditor/plugins/kcfinder|admin/editor/kcfinder|admin/kcfinder|assets/kcfinder)/upload.php'
        - '/xmlrpc.php'
        - '/vendor/phpunit/phpunit/phpunit.xsd'
        - '/lib/phpunit/'
        - '/phpunit/'
        - '/wp-includes/wlwmanifest.xml'
        - '/(admin|administrator|root)/index.php'
        - '/admin/ckfinder/'
        - '/FCKeditor/fckconfig.js'
        - '/data/admin/'
        - '/administrator/(help|language)/'
        - '/js/kcfinder/browse.php'
        - '/new_license.php'
        - '/license.txt'
        - '/administrator/'
        - '/.env'
        - '/.bitcoin'
        - '/wallet.dat'
        - '/backup/wallet.dat'
        - '/components/'
        - '/tmp/'
        - '/plugin/system/debug/'
        - '/router.php'
        - '/ueditor/net/controller.ashx'
        - '/mysql/'
        - '/(phpMyAdmin|myadmin|pma)/'
        - '/(data/admin|data|admin)/allowurl.txt'
        - '/infusions/mp3player_panel/upload.php'
        - '/(assets|files)/uploadify/uploadify.php'
        - '/config/database.yml'

aurora.controller.pwa.favicon:
    controller: 'aurora.controller.pwa:progressiveWebApplication'
    path:
        - '/favicon.ico'
        - '/favicon-{width<\d+>}x{height<\d+>}.png'
        - '/android-icon-{width<\d+>}x{height<\d+>}.png'
        - '/android-icon-maskable.png'
        - '/apple-icon.png'
        - '/apple-icon-precomposed.png'
        - '/apple-icon-precomposed-{width<\d+>}x{height<\d+>}.png'
        - '/apple-icon-{width<\d+>}x{height<\d+>}.png'
        - '/apple-icon-{width<\d+>}x{height<\d+>}-precomposed.png'
        - '/apple-touch-icon-{width<\d+>}x{height<\d+>}.png'
        - '/apple-touch-icon-{width<\d+>}x{height<\d+>}-precomposed.png'
        - '/ms-icon-{width<\d+>}x{height<\d+>}.png'
        - '/manifest.webmanifest'
        - '/manifest.json'
        - '/browserconfig.xml'
        - '/IEconfig.xml'
        - '/pwa-main.js'
        - '/pwa-sw.js'

aurora.controller.pwa.offline:
    controller: 'aurora.controller.pwa:offline'
    path:
        - '/aurora/pwa-offline'
        - '/pwa-offline'

aurora.controller.compiled:
    controller: 'aurora.controller.compiled:cssJsFiles'
    path:
        - '/aurora/compiled/{fileName}'
        #- '/aurora/compiled/{fileName}.(css|js)'

# Extra routes, see `src/Resources/config/services.yaml` & `Sindla\Bundle\AuroraBundle\DependencyInjection\ExtraLoader`
aurora_extra:
    resource: .
    type: extra