parameters:
    aurora.bundle:     'App'
    aurora.root:       '%kernel.project_dir%'
    aurora.tmp:        '%kernel.project_dir%/vendor/sindla/aurora/var/tmp'
    aurora.resources:  '%kernel.project_dir%/vendor/sindla/aurora/var/resources'
    aurora.static:     '%kernel.project_dir%/public/static'
    aurora.locales:    ['en', 'ro']
    aurora.locale:     'ro'
    # maxmind.com license key
    aurora.maxmind.license_key: '%env(default::MAXMIND_LICENSE_KEY)%'
    # Minify output
    aurora.minify.output:                     true
    aurora.minify.output.ignore.extensions:   ['.pdf', '.jpg', '.png', '.gif', '.doc']
    aurora.minify.output.ignore.content.type: ['text/plain']
    # https://developers.google.com/web/fundamentals/web-app-manifest
    aurora.pwa.version_append:          "!php/eval `date('Y-m-d')`"
    aurora.pwa.automatically_prompt:    false
    aurora.pwa.app_name:                'example.com'
    aurora.pwa.app_short_name:          'Example App Name'
    aurora.pwa.app_description:         'Example - this is just an example text'
    aurora.pwa.start_url:               '/?pwa'
    aurora.pwa.display:                 'fullscreen'   # fullscreen | standalone | minimal-ui
    aurora.pwa.icons:                   '%kernel.project_dir%/public/static/img/favicon'
    aurora.pwa.theme_color:             '#2C3E50' # Sets the color of the tool bar, and may be reflected in the app's preview in task switchers
    aurora.pwa.background_color:        '#2C3E50' # Should be the same color as the load page, to provide a smooth transition from the splash screen to your app
    aurora.pwa.offline:                 '/pwa-offline'
    aurora.pwa.precache:
        - '/'
    aurora.pwa.prevent_cache:
        - '/ajax-requests'
        - '/q'
        - '/xhr'
        - '/login'
        - '/logout'
        - '/admin'
    aurora.pwa.external_cache:
        - 'fonts.gstatic.com'
        - 'fonts.googleapis.com'
    aurora.dns_prefetch:
        - 'fonts.googleapis.com'
        - 'googletagmanager.com'
        - 'www.googletagmanager.com'
        - 'gstatic.com'
        - 'google.com'
        - 'google.ro'
        - 'youtube.com'
        - 'addthis.com'
        - 'gemius.pl'
        - 'pubmatic.com'
        - 'innovid.com'
        - 'everesttech.net'
        - 'quantserve.com'
        - 'rubiconproject.com'
        - 'facebook.com'
        - 'agkn.com'
        - 'casalemedia.com'
