services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    #Borealis\Controller\:
        #resource: 'src/Controller/'
        #tags: ['controller.service_arguments']

#    BorealisBundleControllers:
#        resource: Sindla\Bundle\BorealisBundle\Controller
#        type:     annotation

#    borealis.controller.pwa:
#        class: Sindla\Bundle\BorealisBundle\Controller\PWAController
#        autowire: true
#        autoconfigure: true
#        public: true

    ###################################################################################################################
    ###  Borealis Commands ############################################################################################

    # Register TestCommand (see class file for the command name)
    borealis.command.test:
        class: Sindla\Bundle\BorealisBundle\Command\TestCommand
        tags:
            - { name: console.command }

    # Register LazyEntity command (see class file for the command name)
    borealis.command.lazy_entity:
        class: Sindla\Bundle\BorealisBundle\Command\LazyEntityCommand
        arguments: ['@service_container']
        tags:
            - { name: console.command }

    # Register ComposerUpdate command (see class file for the command name)
    borealis.command.composer.update:
        class: Sindla\Bundle\BorealisBundle\Command\ComposerUpdateCommand
        arguments: ['@service_container']
        tags:
            - { name: console.command }

    ###################################################################################################################
    ###  Borealis Twig ################################################################################################

    borealis.twig.utility:
        class: Sindla\Bundle\BorealisBundle\Utils\Twig\UtilityExtension
        tags:
            - { name: twig.extension }
        arguments: ['@service_container', "@request_stack", "@twig"]
        autowire: true
        autoconfigure: true
        public: true

    ###################################################################################################################
    ###  Borealis Services / Utils ####################################################################################

    borealis.calculus:
        class: Sindla\Bundle\BorealisBundle\Utils\Calculus\Calculus
        autowire: true
        autoconfigure: true
        public: true

    borealis.chronos:
        class: Sindla\Bundle\BorealisBundle\Utils\Chronos\Chronos
        autowire: true
        autoconfigure: true
        public: true

    borealis.client:
        class: Sindla\Bundle\BorealisBundle\Utils\Client\Client
        arguments: ['@service_container']
        autowire: true
        autoconfigure: true
        public: true

    borealis.diacritics:
        class: Sindla\Bundle\BorealisBundle\Utils\Diacritics\Diacritics
        autowire: true
        autoconfigure: true
        public: true

    borealis.git:
        class: Sindla\Bundle\BorealisBundle\Utils\Git\Git
        arguments: ['@service_container']
        autowire: true
        autoconfigure: true
        public: true

    borealis.io:
        class: Sindla\Bundle\BorealisBundle\Utils\IO\IO
        autowire: true
        autoconfigure: true
        public: true

#   DEPRECATED
#    borealis.params:
#        class: Sindla\Bundle\BorealisBundle\Utils\Params\Params
#        arguments: ['@service_container']
#        autowire: true
#        autoconfigure: true
#        public: true

    borealis.pwa:
        class: Sindla\Bundle\BorealisBundle\Utils\PWA\PWA
        arguments: ['@service_container', "@twig"]
        autowire: true
        autoconfigure: true
        public: true

    borealis.sanitizer:
        class: Sindla\Bundle\BorealisBundle\Utils\Sanitizer\Sanitizer
        arguments: ['@service_container']
        autowire: true
        autoconfigure: true
        public: true

    borealis.strink:
        class: Sindla\Bundle\BorealisBundle\Utils\Strink\Strink
        autowire: true
        autoconfigure: true
        public: true

    ###################################################################################################################
    ###################################################################################################################