name: PHP Composer

on:
    push:
        branches: [ "5.2" ]
    pull_request:
        branches: [ "5.2" ]

env:
    fail-fast: true
    PHPUNIT_FLAGS: "-v"
    SYMFONY_PHPUNIT_DIR: "$HOME/symfony-bridge/.phpunit"
    SYMFONY_REQUIRE: ">=4.4"

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: "Validate composer.json and composer.lock"
                run: composer validate

#            -   name: "Cache Composer packages"
#                id: composer-cache
#                uses: actions/cache@v2
#                with:
#                    path: vendor
#                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#                    restore-keys: |
#                        ${{ runner.os }}-php-

            -   name: "Install dependencies"
#                if: steps.composer-cache.outputs.cache-hit != 'true'
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: "Install PHPUnit"
                run: vendor/bin/simple-phpunit install

            -   name: "PHPUnit version"
                run: vendor/bin/simple-phpunit --version

#            -   name: "Install symfony"
#                run: composer install symfony/website-skeleton:5.2

            -   name: "Run tests"
                run: vendor/bin/simple-phpunit ${{ env.PHPUNIT_FLAGS }} tests/

        # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
        # Docs: https://getcomposer.org/doc/articles/scripts.md

        # - name: Run test suite
        #   run: composer run-script test